IL--ParameterSharingNO--PartialObsYES--HeterogeneityNO: 
  IL1: 
    label: IL -- Parameter Sharing NO -- Partial Obs YES -- Heterogeneity NO  
    filename: /home/nikunj/work/HAMMER/temp/logs/IL-partialobsyes--sharedparamsno--heterogeneityno-/events.out.tfevents.1611169046.gra627

  HAMMER7: 
    label: Hammer Prev Actions YES --continuousmes-- Meslen 1
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsyes--sharedparamsno--heterogeneityno--continuousmes--meslen1-/events.out.tfevents.1611176978.gra598

  HAMMER6: 
    label: Hammer Prev Actions NO --discretemes-- Meslen 6 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsyes--sharedparamsno--heterogeneityno--meslen6-/events.out.tfevents.1611168378.gra744

  HAMMER2: 

    label: Hammer Prev Actions NO --continuousmes-- Meslen 6 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsyes--sharedparamsno--heterogeneityno--continuousmes--meslen6-/events.out.tfevents.1611176243.gra109 

  HAMMER12: 
    label: Hammer Prev Actions YES --discretemes-- Meslen 6 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsyes--sharedparamsno--heterogeneityno--meslen6-/events.out.tfevents.1611169046.gra129


  # HAMMER4: 
  #   label: Hammer Prev Actions NO -- Partial Obs YES -- Parameter Sharing NO -- Heterogeneity NO  --discretemes-- Meslen 1 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsyes--sharedparamsno--heterogeneityno--meslen1-/events.out.tfevents.1611168378.gra740
  # HAMMER1: 
  #   label: Hammer Prev Actions NO -- Partial Obs YES -- Parameter Sharing NO -- Heterogeneity NO  --continuousmes-- Meslen 1 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsyes--sharedparamsno--heterogeneityno--continuousmes--meslen1-/events.out.tfevents.1611176243.gra724 
  # HAMMER2: 
  #   label: Hammer Prev Actions NO -- Partial Obs YES -- Parameter Sharing NO -- Heterogeneity NO  --continuousmes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsyes--sharedparamsno--heterogeneityno--continuousmes--meslen4-/events.out.tfevents.1611176243.gra736  
  # HAMMER5: 
  #   label: Hammer Prev Actions NO -- Partial Obs YES -- Parameter Sharing NO -- Heterogeneity NO  --discretemes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsyes--sharedparamsno--heterogeneityno--meslen4-/events.out.tfevents.1611168378.gra740
  # HAMMER8: 
  #   label: Hammer Prev Actions YES -- Partial Obs YES -- Parameter Sharing NO -- Heterogeneity NO  --continuousmes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsyes--sharedparamsno--heterogeneityno--continuousmes--meslen4-/events.out.tfevents.1611176977.gra649
  # HAMMER9: 
  #   label: Hammer Prev Actions YES -- Partial Obs YES -- Parameter Sharing NO -- Heterogeneity NO  --continuousmes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsyes--sharedparamsno--heterogeneityno--continuousmes--meslen6-/events.out.tfevents.1611176978.gra706
  # HAMMER10: 
  #   label: Hammer Prev Actions YES --discretemes-- Meslen 1 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsyes--sharedparamsno--heterogeneityno--meslen1-/events.out.tfevents.1611168736.gra136
  # HAMMER11: 
  #   label: Hammer Prev Actions YES --discretemes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsyes--sharedparamsno--heterogeneityno--meslen4-/events.out.tfevents.1611168736.gra138

IL--ParameterSharingNO--PartialObsNO--HeterogeneityNO: 
  IL2: 

    label: IL -- Parameter Sharing NO -- Partial Obs NO -- Heterogeneity NO  
    filename: /home/nikunj/work/HAMMER/temp/logs/IL-partialobsno--sharedparamsno--heterogeneityno-/events.out.tfevents.1611169045.gra1142 

  HAMMER5: 
    label: Hammer Prev Actions NO --discretemes-- Meslen 4 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityno--meslen4-/events.out.tfevents.1611167754.gra645

  HAMMER4: 
    label: Hammer Prev Actions NO --discretemes-- Meslen 1 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityno--meslen1-/events.out.tfevents.1611168060.gra645
  
  HAMMER1: 
    label: Hammer Prev Actions NO --continuousmes-- Meslen 1
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityno--continuousmes--meslen1-/events.out.tfevents.1611175920.gra138
  
  HAMMER10: 
    label: Hammer Prev Actions YES --discretemes-- Meslen 1 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityno--meslen1-/events.out.tfevents.1611168378.gra744

  HAMMER7: 
    label: Hammer Prev Actions YES --continuousmes-- Meslen 1
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityno--continuousmes--meslen1-/events.out.tfevents.1611176243.gra122
  
  HAMMER8: 
    label: Hammer Prev Actions YES --continuousmes-- Meslen 4
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityno--continuousmes--meslen4-/events.out.tfevents.1611176243.gra124

  # HAMMER2: 
  #   label: Hammer Prev Actions NO --continuousmes-- Meslen 4
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityno--continuousmes--meslen4-/events.out.tfevents.1611175921.gra134

  # HAMMER3: 
  #   label: Hammer Prev Actions NO --continuousmes-- Meslen 6
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityno--continuousmes--meslen6-/events.out.tfevents.1611175921.gra134

  # HAMMER6: 
  #   label: Hammer Prev Actions NO --discretemes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityno--meslen6-/events.out.tfevents.1611168378.gra741

  # HAMMER9: 
  #   label: Hammer Prev Actions YES --continuousmes-- Meslen 6
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityno--continuousmes--meslen6-/events.out.tfevents.1611176594.gra646
  
  # HAMMER11: 
  #   label: Hammer Prev Actions YES --discretemes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityno--meslen4-/events.out.tfevents.1611168378.gra319

  # HAMMER12: 
  #   label: Hammer Prev Actions YES --discretemes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityno--meslen6-/events.out.tfevents.1611168378.gra292

IL--ParameterSharingNO--PartialObsNO--HeterogeneityYES: 
  IL3: 
    label: IL -- Parameter Sharing NO -- Partial Obs NO -- Heterogeneity YES  
    filename: /home/nikunj/work/HAMMER/temp/logs/IL-partialobsno--sharedparamsno--heterogeneityyes-/events.out.tfevents.1611169045.gra1144 

  HAMMER4: 
    label:  Hammer Prev Actions NO --discretemes-- Meslen 1 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityyes--meslen1-/events.out.tfevents.1611167753.gra783

  # HAMMER6: 
  #   label:  Hammer Prev Actions NO --discretemes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityyes--meslen6-/events.out.tfevents.1611167752.gra739

  HAMMER1: 
    label:  Hammer Prev Actions NO --continuousmes-- Meslen 1
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityyes--continuousmes--meslen1-/events.out.tfevents.1611175922.gra134

  # HAMMER2: 
    # label:  Hammer Prev Actions NO --continuousmes-- Meslen 4 
    # filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityyes--continuousmes--meslen4-/events.out.tfevents.1611175921.gra134


  HAMMER7: 
    label: Hammer Prev Actions YES --continuousmes-- Meslen 1 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityyes--continuousmes--meslen1-/events.out.tfevents.1611176594.gra649


  
  # HAMMER3: 
  #   label:  Hammer Prev Actions NO --continuousmes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityyes--continuousmes--meslen6-/events.out.tfevents.1611175921.gra134

  # HAMMER5: 
  #   label:  Hammer Prev Actions NO --discretemes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsno--partialobsno--sharedparamsno--heterogeneityyes--meslen4-/events.out.tfevents.1611167752.gra739

  # HAMMER8: 
  #   label: Hammer Prev Actions YES --continuousmes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityyes--continuousmes--meslen4-/events.out.tfevents.1611176596.gra1069
  # HAMMER9: 
  #   label: Hammer Prev Actions YES --continuousmes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityyes--continuousmes--meslen6-/events.out.tfevents.1611176595.gra1054

  HAMMER10: 
    label: Hammer Prev Actions YES --discretemes-- Meslen 1 
    filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityyes--meslen1-/events.out.tfevents.1611168378.gra292
  # HAMMER11: 
  #   label: Hammer Prev Actions YES --discretemes-- Meslen 4 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityyes--meslen4-/events.out.tfevents.1611168733.gra648
  # HAMMER12: 
  #   label: Hammer Prev Actions YES --discretemes-- Meslen 6 
  #   filename: /home/nikunj/work/HAMMER/temp/logs/hammer-prevactionsyes--partialobsno--sharedparamsno--heterogeneityyes--meslen6-/events.out.tfevents.1611168735.gra130
