global:
  K_epochs: 80
  action_std: 0.5
  hidden_nodes: 64
  lr: 0.0003
  update_timestep: 4000
local:
  K_epochs: 4
  lr: 0.01
  n_latent_var: 64
  update_timestep: 2000
main:
  env_name: Cooperative_Navigation
  eps_clip: 0.2
  exp_name: cn-main-agents_3-rs_10
  gamma: 0.95
  log_dir: logs/
  log_interval: 20
  max_episodes: 30000
  max_timesteps: 25
  message_len: 4
  random_seed: 10
  render: false
  save_dir: save-dir/
  save_interval: 50
  solved_reward: 0.0
