global:
  K_epochs: 80
  action_std: 0.5
  hidden_nodes: 64
  lr: 0.0003
  update_timestep: 4000
local:
  K_epochs: 80
  action_std: 0.5
  hidden_nodes: 64
  lr: 0.0003
  update_timestep: 4000
main:
  eps_clip: 0.2
  exp_name: mw-baseline-agents_3-rs_15
  gamma: 0.95
  logdir: logs/
  log_interval: 20
  main: 0
  max_episodes: 10000
  max_timesteps: 25
  message_len: 8
  n_walkers: 3
  random_seed: 15
  save_dir: save-dir/
  save_interval: 50
